# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import google.protobuf.descriptor_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='muduo/protorpc2/rpc2.proto',
  package='rpc2',
  serialized_pb='\n\x1amuduo/protorpc2/rpc2.proto\x12\x04rpc2\x1a google/protobuf/descriptor.proto\"\x07\n\x05\x45mpty:3\n\nidempotent\x12\x1e.google.protobuf.MethodOptions\x18\xd7\x08 \x01(\x08:1\n\x08noreturn\x12\x1e.google.protobuf.MethodOptions\x18\xd8\x08 \x01(\x08\x42(\n\x1b\x63om.chenshuo.muduo.protorpcB\tRpc2Proto')


IDEMPOTENT_FIELD_NUMBER = 1111
idempotent = descriptor.FieldDescriptor(
  name='idempotent', full_name='rpc2.idempotent', index=0,
  number=1111, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
NORETURN_FIELD_NUMBER = 1112
noreturn = descriptor.FieldDescriptor(
  name='noreturn', full_name='rpc2.noreturn', index=1,
  number=1112, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_EMPTY = descriptor.Descriptor(
  name='Empty',
  full_name='rpc2.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=70,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY

class Empty(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMPTY
  
  # @@protoc_insertion_point(class_scope:rpc2.Empty)

google.protobuf.descriptor_pb2.MethodOptions.RegisterExtension(idempotent)
google.protobuf.descriptor_pb2.MethodOptions.RegisterExtension(noreturn)
# @@protoc_insertion_point(module_scope)
