# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='rpc.proto',
  package='muduo.net',
  serialized_pb='\n\trpc.proto\x12\tmuduo.net\"\xa7\x01\n\nRpcMessage\x12$\n\x04type\x18\x01 \x02(\x0e\x32\x16.muduo.net.MessageType\x12\n\n\x02id\x18\x02 \x02(\x06\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\x0e\n\x06method\x18\x04 \x01(\t\x12\x0f\n\x07request\x18\x05 \x01(\x0c\x12\x10\n\x08response\x18\x06 \x01(\x0c\x12#\n\x05\x65rror\x18\x07 \x01(\x0e\x32\x14.muduo.net.ErrorCode*3\n\x0bMessageType\x12\x0b\n\x07REQUEST\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\x12\t\n\x05\x45RROR\x10\x03*t\n\tErrorCode\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x0f\n\x0bWRONG_PROTO\x10\x01\x12\x0e\n\nNO_SERVICE\x10\x02\x12\r\n\tNO_METHOD\x10\x03\x12\x13\n\x0fINVALID_REQUEST\x10\x04\x12\x14\n\x10INVALID_RESPONSE\x10\x05\x42\'\n\x1b\x63om.chenshuo.muduo.protorpcB\x08RpcProto')

_MESSAGETYPE = descriptor.EnumDescriptor(
  name='MessageType',
  full_name='muduo.net.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='REQUEST', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=194,
  serialized_end=245,
)


_ERRORCODE = descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='muduo.net.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WRONG_PROTO', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NO_SERVICE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NO_METHOD', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INVALID_REQUEST', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INVALID_RESPONSE', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=247,
  serialized_end=363,
)


REQUEST = 1
RESPONSE = 2
ERROR = 3
NO_ERROR = 0
WRONG_PROTO = 1
NO_SERVICE = 2
NO_METHOD = 3
INVALID_REQUEST = 4
INVALID_RESPONSE = 5



_RPCMESSAGE = descriptor.Descriptor(
  name='RpcMessage',
  full_name='muduo.net.RpcMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='muduo.net.RpcMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='muduo.net.RpcMessage.id', index=1,
      number=2, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='service', full_name='muduo.net.RpcMessage.service', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='method', full_name='muduo.net.RpcMessage.method', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='request', full_name='muduo.net.RpcMessage.request', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='response', full_name='muduo.net.RpcMessage.response', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='muduo.net.RpcMessage.error', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=192,
)

_RPCMESSAGE.fields_by_name['type'].enum_type = _MESSAGETYPE
_RPCMESSAGE.fields_by_name['error'].enum_type = _ERRORCODE
DESCRIPTOR.message_types_by_name['RpcMessage'] = _RPCMESSAGE

class RpcMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPCMESSAGE
  
  # @@protoc_insertion_point(class_scope:muduo.net.RpcMessage)

# @@protoc_insertion_point(module_scope)
