# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rpc_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='rpcservice.proto',
  package='muduo.net',
  serialized_pb='\n\x10rpcservice.proto\x12\tmuduo.net\x1a\trpc.proto\";\n\x0eListRpcRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x13\n\x0blist_method\x18\x02 \x01(\x08\"a\n\x0fListRpcResponse\x12#\n\x05\x65rror\x18\x01 \x02(\x0e\x32\x14.muduo.net.ErrorCode\x12\x14\n\x0cservice_name\x18\x02 \x03(\t\x12\x13\n\x0bmethod_name\x18\x03 \x03(\t\")\n\x11GetServiceRequest\x12\x14\n\x0cservice_name\x18\x01 \x02(\t\"f\n\x12GetServiceResponse\x12#\n\x05\x65rror\x18\x01 \x02(\x0e\x32\x14.muduo.net.ErrorCode\x12\x12\n\nproto_file\x18\x02 \x03(\t\x12\x17\n\x0fproto_file_name\x18\x03 \x03(\t2\x99\x01\n\nRpcService\x12@\n\x07listRpc\x12\x19.muduo.net.ListRpcRequest\x1a\x1a.muduo.net.ListRpcResponse\x12I\n\ngetService\x12\x1c.muduo.net.GetServiceRequest\x1a\x1d.muduo.net.GetServiceResponseB7\n\x1b\x63om.chenshuo.muduo.protorpcB\x0fRpcServiceProto\x80\x01\x01\x88\x01\x01\x90\x01\x01')




_LISTRPCREQUEST = descriptor.Descriptor(
  name='ListRpcRequest',
  full_name='muduo.net.ListRpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='service_name', full_name='muduo.net.ListRpcRequest.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='list_method', full_name='muduo.net.ListRpcRequest.list_method', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=101,
)


_LISTRPCRESPONSE = descriptor.Descriptor(
  name='ListRpcResponse',
  full_name='muduo.net.ListRpcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='muduo.net.ListRpcResponse.error', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='service_name', full_name='muduo.net.ListRpcResponse.service_name', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='method_name', full_name='muduo.net.ListRpcResponse.method_name', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=103,
  serialized_end=200,
)


_GETSERVICEREQUEST = descriptor.Descriptor(
  name='GetServiceRequest',
  full_name='muduo.net.GetServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='service_name', full_name='muduo.net.GetServiceRequest.service_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=202,
  serialized_end=243,
)


_GETSERVICERESPONSE = descriptor.Descriptor(
  name='GetServiceResponse',
  full_name='muduo.net.GetServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='muduo.net.GetServiceResponse.error', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='proto_file', full_name='muduo.net.GetServiceResponse.proto_file', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='proto_file_name', full_name='muduo.net.GetServiceResponse.proto_file_name', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=245,
  serialized_end=347,
)

_LISTRPCRESPONSE.fields_by_name['error'].enum_type = rpc_pb2._ERRORCODE
_GETSERVICERESPONSE.fields_by_name['error'].enum_type = rpc_pb2._ERRORCODE
DESCRIPTOR.message_types_by_name['ListRpcRequest'] = _LISTRPCREQUEST
DESCRIPTOR.message_types_by_name['ListRpcResponse'] = _LISTRPCRESPONSE
DESCRIPTOR.message_types_by_name['GetServiceRequest'] = _GETSERVICEREQUEST
DESCRIPTOR.message_types_by_name['GetServiceResponse'] = _GETSERVICERESPONSE

class ListRpcRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LISTRPCREQUEST
  
  # @@protoc_insertion_point(class_scope:muduo.net.ListRpcRequest)

class ListRpcResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LISTRPCRESPONSE
  
  # @@protoc_insertion_point(class_scope:muduo.net.ListRpcResponse)

class GetServiceRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETSERVICEREQUEST
  
  # @@protoc_insertion_point(class_scope:muduo.net.GetServiceRequest)

class GetServiceResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETSERVICERESPONSE
  
  # @@protoc_insertion_point(class_scope:muduo.net.GetServiceResponse)


_RPCSERVICE = descriptor.ServiceDescriptor(
  name='RpcService',
  full_name='muduo.net.RpcService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=350,
  serialized_end=503,
  methods=[
  descriptor.MethodDescriptor(
    name='listRpc',
    full_name='muduo.net.RpcService.listRpc',
    index=0,
    containing_service=None,
    input_type=_LISTRPCREQUEST,
    output_type=_LISTRPCRESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='getService',
    full_name='muduo.net.RpcService.getService',
    index=1,
    containing_service=None,
    input_type=_GETSERVICEREQUEST,
    output_type=_GETSERVICERESPONSE,
    options=None,
  ),
])

class RpcService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _RPCSERVICE
class RpcService_Stub(RpcService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _RPCSERVICE

# @@protoc_insertion_point(module_scope)
